version: "3.8"

services:
  web:
    build: .
    image: fastapi-url-shortener
    container_name: fastapi-url-shortener
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
